stages:
  build_features:
    cmd: python src/features/features.py
    deps:
      - data/raw
      - src/features/features.py
    outs:
      - data/processed/final_training.csv
  train:
    cmd: python src/model/train.py
    deps:
      - data/processed/final_training.csv
      - src/model/train.py
    outs:
      - models/gradient_boosting.pkl
